name: tiny_satoshi
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  bonfire: ^3.14.0
  flutter_bloc: ^9.1.1
  qr_flutter: ^4.1.0
  fluttertoast: ^8.2.12
  url_launcher: ^6.3.1
  logging: ^1.3.0
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_secure_storage: ^9.2.4
  bdk_flutter: ^0.30.0
  connectivity_plus: ^6.1.4
  bip39: ^1.0.6
  collection: ^1.19.1
  flame_audio: ^2.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audio/
    - assets/images/
    - assets/images/background/
    - assets/images/player/
    - assets/images/tiled/
    - assets/images/emote/
    - assets/images/items/
    - assets/images/npc/
    - assets/images/enemy/
    - assets/images/enemy/goblin/
    - assets/images/enemy/imp/
    - assets/images/enemy/mini_boss/
    - assets/images/enemy/boss/

  fonts:
    - family: Normal
      fonts:
        - asset: fonts/font_pixel.ttf
